export const entityTypes = [
  "Advanced Technology",
  "Adventure",
  "Aircraft",
  "Armor",
  "Artifact",
  "Building",
  "Campaign",
  "Castle",
  "Cave",
  "Celestial Body",
  "Character",
  "City",
  "Civilization",
  "Continent",
  "Creature",
  "Culture",
  "District",
  "Deity",
  "Dungeon",
  "Encounter",
  "Equipment",
  "Event",
  "Faction",
  "Galaxy",
  "Geographical feature",
  "Item",
  "Landmark",
  "Language",
  "Magic System",
  "Magical Item",
  "Monster",
  "Monument",
  "Mythical Creature",
  "Neighborhood",
  "NPC",
  "Organization",
  "Pantheon",
  "Planet",
  "Plant",
  "Plot",
  "Quest",
  "Region",
  "Religion",
  "Roleplaying Class",
  "Ruins",
  "Sentient Species",
  "Settlement",
  "Ship",
  "Spacecraft",
  "Special Location",
  "Species",
  "Spell",
  "Star System",
  "Story",
  "Structure",
  "Tavern/Inn",
  "Tome",
  "Town",
  "Tree",
  "Universe",
  "Vehicle",
  "Weapon",
  "Other",
];
